name: 'github actions getjson'

on:
  push:

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout codes'
        uses: actions/checkout@v2

      - name: 'run_sh'
        run: req.sh
        shell: bash
      
      