name: 'github actions getjson'

on:
  push:
  schedule:
    - cron: '0 1,10 * * *'

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout codes'
        uses: actions/checkout@v2

      - name: 'run_sh'
        run: ./req.sh
        shell: bash
      
      